# Generated by Django 3.0.3 on 2025-11-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0003_auto_20251109_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
