# Generated by Django 3.0.3 on 2025-11-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_auto_20251108_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencing',
            old_name='senquency_factory',
            new_name='sequencing_factory',
        ),
    ]
